---
title: "Lab-02-PECK"
author: "April peck"
date: "10/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#libraries
library(dplyr)
library(here)
library(pander)
```



```{r}

#data

# store data dictionary file path
DD_FILEPATH <- here::here( "data/rodeo/ltdb_data_dictionary.csv" )

# import data dictionary
dd <- read.csv( DD_FILEPATH, stringsAsFactors=F )

# longitudinal tract data base 2010 sample
ltdb.data <- read.csv(here("data/raw/ltdb_std_2010_sample.csv"))

# rename columns to lowercase
ltdb.data <- as.data.frame( sapply(ltdb.data, tolower))
```


## Functions
```{r}
# load function source files
source(here("analysis/utilities.R"))
```

```{r}
# test helper functions

# search by category
head(category_search(dd, "language"))
head(category_search(dd, c("language", "race")))


# keyword search
head(search_word(dd, "income"))
head(search_word(dd, c("income", "female")))

# search by year(s)
head(search_years(dd, year = c("1970", "1980", "1990", "2000")))
head(search_years(dd, year = c("1970","1990")))
head(search_years(dd, "1980"))
```

