---
title: "Lab02-AhmedRashwan"
output:
  html_document:
    theme: readable
    highlight: zenburn
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, results = 'asis')
```

```{r, eval=FALSE}

# Install necessary packages
install.packages("here")

```

### Running Needed Packages 

```{r, results='hide'}

# load necessary packages
library( tidyverse )
library( here )
library( pander )
library( tidycensus )

```

### Part 1: Data Concordance

```{r}
# Reading data files from specific file paths in my desktop


# store data dictionary file path
DD_FILEPATH <- here::here("data/raw/Ahmeds-ltdb_data_dictionary.csv")

# import data dictionary
dd <- read.csv(DD_FILEPATH , header=T,fill=T , stringsAsFactors=F)
head(dd) %>% pander()

```

```{r}

# rename columns to lower case in both data frames 


dd <- as.data.frame( sapply( dd, tolower) )

ltdb.data <- as.data.frame( sapply( dd, tolower) )

# view a subset of columns 
dd[ c(1:5,15:17), ] %>% pander()

```

### Part 2: Build a Variable Filter


### Loading functions from utilities.R file

```{r, results='hide'}

# Loading functions from source files

source(here::here("analysis/utilities_master.R"))

```

### Running functions 

```{r , warning=FALSE}
# Run the date function

today()

cat_filter(dd,c("age", "race")) %>% head(10) %>% pander 

search_description(dd , "*income*") %>% head() %>% pander

search_years(dd, year = c("1990", "2000", "2010")) %>% head(20) %>% pander

```
