---
title: 'CPP 528 Lab 02: Data Management'
author: "Erin McIntyre"
date: "10/27/2021"
output:
   html_document:
    theme: readable
    df_print: paged
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# Library

library(dplyr)
library(here)
library(tidyverse)

```
## Load data dictionary

```{r}

# store data dictionary file path
DD_FILEPATH <- here::here( "data/rodeo/ltdb_data_dictionary.csv")

# import data dictionary
dd <- read.csv( DD_FILEPATH, stringsAsFactors=F, fileEncoding = "UTF-8-BOM")

# remove extra columns from data frame
clean.dd = subset(dd, select = -c(X, X.1, X.2, X.3, X.4, X.5, X.6, X.7))

```


## Functions


```{r}
# Load function source files.

source(here("analysis/utilities.R"))
source(here("analysis/helper_functions_em.R"))


```


## Variable Filter One 


```{r}

# Run filter data function

search.terms <- c("age")

filter_data(clean.dd, search.terms)

```


## Variable Filter Two


```{r}
# Run keyword function

keyword_search( clean.dd, "housing")


```


## Variable Filter Three Attempts


```{r}

# List column names to identify columns containing time variables.

colnames(clean.dd)

```


```{r}
# Run filter time period function resulting in error message.

# chosen.time <- c("80", "90")
# filter_time_period(clean.dd, chosen.time)

# error message: Error in grepl(chosen.time, data$X1970.f, data$X1970.s, data$X1980.f,  
#: unused arguments (data$X1990.s, data$X2000.f, data$X2000.s, data$X2010.f, data$X2010.s)

```


```{r}

# Partial success using one column and variable for time periods.

chosen.time <- c("80")

filter_decade <- function( data, chosen.time)
{
  
  filtered.time <- grepl( chosen.time, data$X1980.s) # function to search time period variables for the chosen time
  data.time.period <- data [ filtered.time, c("root", "root2", "category", "definition")]
  
  return(data.time.period) # returns a table of variables for that chosen time
}

filter_decade(clean.dd, chosen.time) 
 

```


