---
title: "Lab02-AhmedRashwan"
author: "Ahmed Rashwan"
date: "10/27/2021"
output:
  md_document:
    variant: gfm
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, eval=FALSE}

# Install necessary packages
install.packages("here")

```


### Running Needed Packages 


```{r , warning=FALSE}

# load necessary packages
library( tidyverse )
library( here )
library( pander )


```


### Part 1: Data Concordance


```{r , , warning=FALSE}
# Reading data files from specific file paths in my desktop


# store data dictionary file path
DD_FILEPATH <- here::here("data/raw/Ahmeds-ltdb_data_dictionary.csv")

# import data dictionary
dd <- read.csv(DD_FILEPATH , header=T,fill=T , stringsAsFactors=F)
head(dd) %>% pander()

```

```{r , , warning=FALSE}

# rename columns to lower case in both data frames 


dd <- as.data.frame( sapply( dd, tolower) )

ltdb.data <- as.data.frame( sapply( dd, tolower) )

# view a subset of columns 
dd[ c(1:5,15:17), ] %>% pander()

```


### Part 2: Build a Variable Filter


### Loading functions from utilities_master.R file

```{r , warning=FALSE}

# Loading functions from source files

import::here("today",
             "cat_filter",
             "search_description",
             "search_years",
             # notice the use of here::here() that points to the .R file
             # where all these R objects are created
             .from = here::here("analysis/utilities_master.R"),
             .character_only = TRUE)
```

### Run functions 

```{r , warning=FALSE}
# Run the date function

today()

#### cat_filter () function that takes as an argument one or more of the groups that we just created in the concordance file under the “category” field and returns all of the variables associated with that group.

cat_filter(dd,c("age", "race")) %>% head(10) %>% pander 


#### search_description () function that searches variable descriptions for a specific string and returns any variables that match. For example, if I searched for “income” I would want variables like median household income and per capita income.

search_description(dd , "*income*") %>% head() %>% pander


#### search_years() function to filter variables by time periods. Specifically, the user will specify the time periods of interest for the study and the function will identify all variables that have measures for those periods. For example, I if I want to use the data for a study that covers 1990, 2000, and 2010 which variables are available for all three periods

search_years(dd, year = c("1990", "2000", "2010")) %>% head(20) %>% pander

```
