---
title: "S_TYPE Test"
author: "Erin McIntyre"
date: "12/12/2021"
output:
  md_document:
    variant: gfm
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, message=FALSE, warning=FALSE}

# load necessary packages ----
library( dplyr )
library( here )
library( knitr )
library( pander )
library( stargazer )
library( scales )
# set randomization seed ----
set.seed( 1234 )
# load necessary functions and objects ----
# note: all of these are R objects that will be used throughout this .rmd file
import::here("S_TYPE",
             "panel.cor",
             "panel.smooth",
             "jplot",
             "d",
             "df",
             "cbsa_stats_df",
             # notice the use of here::here() that points to the .R file
             # where all these R objects are created
             .from = here::here("analysis/utilities_master.R"),
             .character_only = TRUE)

```


```{r}
# Omit cases that have a median home value less than $10,000 in 2000.
# Omit cases with growth rates above 200%.

d_clean <-
  d %>% 
  filter(mhv.00 > 10000) %>% 
  filter(mhv.growth < 200)

# Select predictors of change in MHV or mhv.growth
d_predict <- select(d_clean, mhv.growth, pov.rate, p.unemp, hinc00, p.white, p.col, p.prof)


# recode some vars to remove outliers and skew
d_predict$p.unemp <- log10( d_predict$p.unemp + 1 )
d_predict$hinc00 <- log10( d_predict$hinc00 + 1 )
d_predict$p.white <- log10( d_predict$p.white + 1  )
d_predict$pov.rate <- log10( d_predict$pov.rate + 1 )
d_predict$p.col <- log10( d_predict$p.col + 1 )
d_predict$p.prof <- log10( d_predict$p.prof + 1 )

```


```{r muticollinearity test 1}

# Test for multicollinearity

m1 <- lm( mhv.growth ~  pov.rate, data=d_predict )
m2 <- lm( mhv.growth ~  p.unemp, data=d_predict )
m3 <- lm( mhv.growth ~  p.white, data=d_predict )
m4 <- lm( mhv.growth ~  p.prof, data=d_predict )
m5 <- lm( mhv.growth ~  pov.rate + p.unemp + p.white + p.prof, data=d_predict )

stargazer( m1, m2, m3, m4, m5,
           type=S_TYPE, digits=2,
           omit.stat = c("rsq","f") )


```



```{r multicollinearity test 2}
# Remove p.unemp and run the regression model again. 

m6 <- lm( mhv.growth ~  pov.rate + p.white + p.prof, data=d_predict )

stargazer( m1, m3, m4, m6,
           type=S_TYPE, digits=2,
           omit.stat = c("rsq","f") )


```



```{r final regression model}
# Add a metro-level control

d_fixed <- 
  d_clean %>%
  group_by( cbsaname ) %>%
  mutate( metro.mhv.growth = 100 * median( mhv.growth, na.rm=T ) ) %>%
  ungroup() 

# Select variables for regression model.
d.reg <- select(d_fixed, mhv.growth, pov.rate, p.white, p.prof, cbsa)


# Perform log transformations
d.reg$p.white <- log10( d.reg$p.white + 1  )
d.reg$pov.rate <- log10( d.reg$pov.rate + 1 )
d.reg$p.prof <- log10( d.reg$p.prof + 1 )

# Regression Model
m1 <- lm( mhv.growth ~  pov.rate, data=d.reg )
m2 <- lm( mhv.growth ~  p.white, data=d.reg )
m3 <- lm( mhv.growth ~  p.prof, data=d.reg )
m4 <- lm( mhv.growth ~  pov.rate + p.white + p.prof + cbsa, data=d.reg )

stargazer( m1, m2, m3, m4,
           type=S_TYPE, digits=2,
           omit.stat = c("rsq","f"),
           omit="cbsa",
           add.lines = list(c("Metro Fixed Effects:", "NO", "NO", "NO", "YES")) )

```




